#!/usr/bin/env bun
/**
 * Build-time generator: embed bundled .sfw firmware files as
 * base64-encoded constants in `axon/src/sfw-embedded.ts`.
 *
 * `bun build --compile` does NOT auto-embed arbitrary file paths
 * into the final binary, but it DOES bake in top-level `import`ed
 * modules. The simplest reliable strategy is therefore:
 *
 *   1. Walk `data/servo_catalog.json` for each model's
 *      `bundled_firmware` entries.
 *   2. For each entry, look for the matching file under
 *      `downloads/` (gitignored vendor drop — the user supplies it).
 *   3. If present, base64-encode the bytes and emit a string constant.
 *   4. If absent, emit `null`.
 *
 * The resulting `sfw-embedded.ts` is listed in `.gitignore`; it is
 * regenerated on every build via the `prebuild` script in
 * `axon/package.json`.
 *
 * Run manually:
 *   cd axon && bun run scripts/embed-sfw.ts
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const AXON_DIR = resolve(__dirname, "..");
const REPO_ROOT = resolve(AXON_DIR, "..");
const CATALOG_PATH = join(REPO_ROOT, "data", "servo_catalog.json");
const DOWNLOADS_DIR = join(REPO_ROOT, "downloads");
const OUTPUT_PATH = join(AXON_DIR, "src", "sfw-embedded.ts");

interface BundledFirmwareEntry {
  file: string;
  sha256: string;
  description?: string;
}

interface CatalogShape {
  models: Record<string, { bundled_firmware?: Record<string, BundledFirmwareEntry> }>;
}

interface EmbedResult {
  modelId: string;
  modeKey: string;
  file: string;
  expectedSha256: string;
  available: boolean;
  actualSha256?: string;
  base64?: string;
  reason?: string;
}

function sha256Hex(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

function loadCatalog(): CatalogShape {
  const raw = readFileSync(CATALOG_PATH, "utf8");
  return JSON.parse(raw) as CatalogShape;
}

function main(): number {
  const catalog = loadCatalog();
  const entries: EmbedResult[] = [];

  for (const [modelId, model] of Object.entries(catalog.models)) {
    // Placeholder models (prefix "_") are still valid sources of
    // bundled firmware file names — the runtime catalog filters them,
    // but the build step should embed every .sfw it can find so the
    // binary is ready if we later add the real model entry.
    const bundled = model.bundled_firmware ?? {};
    for (const [modeKey, entry] of Object.entries(bundled)) {
      const diskPath = join(DOWNLOADS_DIR, entry.file);
      if (!existsSync(diskPath)) {
        entries.push({
          modelId,
          modeKey,
          file: entry.file,
          expectedSha256: entry.sha256,
          available: false,
          reason: `not found at ${diskPath}`,
        });
        continue;
      }
      const bytes = readFileSync(diskPath);
      const actual = sha256Hex(bytes);
      if (actual.toLowerCase() !== entry.sha256.toLowerCase()) {
        entries.push({
          modelId,
          modeKey,
          file: entry.file,
          expectedSha256: entry.sha256,
          actualSha256: actual,
          available: false,
          reason: `sha256 mismatch (catalog says ${entry.sha256}, disk has ${actual})`,
        });
        continue;
      }
      entries.push({
        modelId,
        modeKey,
        file: entry.file,
        expectedSha256: entry.sha256,
        actualSha256: actual,
        available: true,
        base64: bytes.toString("base64"),
      });
    }
  }

  // ---- render the output file ----
  const lines: string[] = [];
  lines.push("// AUTOGENERATED by axon/scripts/embed-sfw.ts — DO NOT EDIT BY HAND.");
  lines.push("// The checked-in copy of this file is an empty stub. Developers run");
  lines.push("// `bun run scripts/embed-sfw.ts` (or `bun run build`, which invokes");
  lines.push("// it via the `prebuild` hook) to re-populate it from downloads/.");
  lines.push("// Do NOT commit the populated version.");
  lines.push("");
  lines.push("export interface EmbeddedFirmware {");
  lines.push("  /** Model id from data/servo_catalog.json (e.g. 'SA33****'). */");
  lines.push("  readonly modelId: string;");
  lines.push("  /** Mode key within the model's bundled_firmware map (e.g. 'standard'). */");
  lines.push("  readonly modeKey: string;");
  lines.push("  /** Canonical .sfw file name (matches the catalog entry). */");
  lines.push("  readonly file: string;");
  lines.push("  /** Expected SHA-256 of the .sfw file from the catalog. */");
  lines.push("  readonly sha256: string;");
  lines.push("  /** Whether this firmware was actually embedded at build time. */");
  lines.push("  readonly available: boolean;");
  lines.push("  /** Base64-encoded .sfw bytes (only set when `available` is true). */");
  lines.push("  readonly base64: string | null;");
  lines.push("  /** Reason the firmware is not available, if `available` is false. */");
  lines.push("  readonly reason: string | null;");
  lines.push("}");
  lines.push("");
  lines.push("export const EMBEDDED_FIRMWARE: readonly EmbeddedFirmware[] = [");
  for (const e of entries) {
    lines.push("  {");
    lines.push(`    modelId: ${JSON.stringify(e.modelId)},`);
    lines.push(`    modeKey: ${JSON.stringify(e.modeKey)},`);
    lines.push(`    file: ${JSON.stringify(e.file)},`);
    lines.push(`    sha256: ${JSON.stringify(e.expectedSha256)},`);
    lines.push(`    available: ${e.available ? "true" : "false"},`);
    if (e.available && e.base64) {
      // Split to keep line width under 100.
      lines.push(`    base64:`);
      const chunks = e.base64.match(/.{1,80}/g) ?? [e.base64];
      for (let i = 0; i < chunks.length; i++) {
        const suffix = i === chunks.length - 1 ? "," : " +";
        lines.push(`      ${JSON.stringify(chunks[i]!)}${suffix}`);
      }
    } else {
      lines.push("    base64: null,");
    }
    if (e.available) {
      lines.push("    reason: null,");
    } else {
      lines.push(`    reason: ${JSON.stringify(e.reason ?? "unavailable")},`);
    }
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  lines.push("/** Look up an embedded firmware entry by model id + mode key. */");
  lines.push("export function findEmbeddedFirmware(");
  lines.push("  modelId: string,");
  lines.push("  modeKey: string,");
  lines.push("): EmbeddedFirmware | undefined {");
  lines.push("  return EMBEDDED_FIRMWARE.find((e) => e.modelId === modelId && e.modeKey === modeKey);");
  lines.push("}");
  lines.push("");

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, lines.join("\n"));

  // Summary to stderr so CI logs show what shipped.
  const available = entries.filter((e) => e.available).length;
  const missing = entries.length - available;
  process.stderr.write(
    `embed-sfw: wrote ${OUTPUT_PATH}\n  ${available} firmware(s) embedded, ${missing} missing\n`,
  );
  for (const e of entries) {
    const tag = e.available ? "OK" : "--";
    process.stderr.write(
      `  [${tag}] ${e.modelId}/${e.modeKey} -> ${e.file}${e.available ? "" : `  (${e.reason})`}\n`,
    );
  }
  return 0;
}

process.exit(main());
