// AUTOGENERATED by axon/scripts/embed-sfw.ts — DO NOT EDIT BY HAND.
// The checked-in copy of this file is an empty stub. Developers run
// `bun run scripts/embed-sfw.ts` (or `bun run build`, which invokes
// it via the `prebuild` hook) to re-populate it from downloads/.
// Do NOT commit the populated version.
//
// This stub lets `bun test` and `bun run src/cli.ts status` run on a
// fresh clone without requiring the vendor .sfw drop in downloads/.
// When no firmware is embedded, `axon mode list` reports "(not
// embedded)" for every entry, and `axon mode set <name>` tells the
// user to regenerate or pass `--file <path>`.

export interface EmbeddedFirmware {
  /** Model id from data/servo_catalog.json (e.g. 'SA33****'). */
  readonly modelId: string;
  /** Mode key within the model's bundled_firmware map (e.g. 'standard'). */
  readonly modeKey: string;
  /** Canonical .sfw file name (matches the catalog entry). */
  readonly file: string;
  /** Expected SHA-256 of the .sfw file from the catalog. */
  readonly sha256: string;
  /** Whether this firmware was actually embedded at build time. */
  readonly available: boolean;
  /** Base64-encoded .sfw bytes (only set when `available` is true). */
  readonly base64: string | null;
  /** Reason the firmware is not available, if `available` is false. */
  readonly reason: string | null;
}

export const EMBEDDED_FIRMWARE: readonly EmbeddedFirmware[] = [];

/** Look up an embedded firmware entry by model id + mode key. */
export function findEmbeddedFirmware(
  modelId: string,
  modeKey: string,
): EmbeddedFirmware | undefined {
  return EMBEDDED_FIRMWARE.find((e) => e.modelId === modelId && e.modeKey === modeKey);
}
